### ISSUE TITLE
TimerTask是异步执行的，这么cancel有问题吧

### ISSUE THREAD

**Issue by Liweiwei2Anna** [getActivity/XToast#1]
Timer.schedule(ToastDismissTask)这个，因为ToastDismissTask是在异步线程里执行的，虽然WindowManager里调用removeView不会出问题，但是cancel涉及到线程同步吧，isShow就会出现状态不准的情况。

**Comment by getActivity** [comment]
我的解决方案是给isShow加上volatile关键字，用于解决线程同步的问题
