### ISSUE TITLE
Toast展示的时候,点击Toast下面的窗口的时候无法点击

### ISSUE THREAD

**Issue by ailuoyang** [getActivity/XToast#11]

**Comment by Lemniscate317** [comment]
你参照demo 有一个可以自由拖拽的选项 加上后就可以点了 然后你自己自定义一个自由拖拽类 不处理拖拽就行

**Comment by 880634** [comment]
你试一下 Demo 有没有出现你说的问题

**Comment by 880634** [comment]
如果还不能解决就到Q群联系我，Github 处理可能没有那么及时

**Comment by ailuoyang** [comment]
好的，方法可行，谢谢！

**Comment by ailuoyang** [comment]
demo也有这个问题，一楼的方法是对的

**Comment by 880634** [comment]
这个问题由于是 flag 没有添加 FLAG_NOT_TOUCH_MODAL 导致的

**Comment by 880634** [comment]
这个问题我会在下个版本进行优化，把默认的 Flag 设置好，减少大部分的人额外去设置 Flag
