### ISSUE TITLE
小米系列手机应用外悬浮弹窗无法启动应用内activtiy

### ISSUE THREAD

**Issue by stonebirds** [getActivity/XToast#15]
就是我用的是悬浮窗，当我收到在系统桌面或者是其他应用内的时候，点击悬浮窗的按钮，无法启动应用的activity，但是在应用内是可以启动的

目前测试华为、1 + 手机应用内外都可以启动activity

请问是什么原因

**Comment by getActivity** [comment]
这个是因为 Android 高版本禁用了应用的某些行为，后台进程企图启动一个前台的 Activity，这个和框架本身没有太大关系，你需要自行适配一下

**Comment by stonebirds** [comment]
> 这个是因为 Android 高版本禁用了应用的某些行为，后台进程企图启动一个前台的 Activity，这个和框架本身没有太大关系，你需要自行适配一下

这个已经适配了，这是因为高版本是有这个权限，尤其是小米手机必须用户授权【后台启动界面】这个权限，但是这个权限有没有API可以进行动态申请，只能是跳转到设置界面让用户手动授权。现目前其他手机机型没有这个限制。
