### ISSUE TITLE
android 6.0版本兼容问题

### ISSUE THREAD

**Issue by Redoteam** [getActivity/XToast#2]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/17085002/54104337-6ff1f380-440a-11e9-892e-12eb7cf82cf4.png">
用Demo测试
6.0以下用activity创建，Toast结束会导致退出程序：测试机系统是Android 4.4.4

6.0以上用Application创建，Toast不会出现：测试机 系统是 Android 8.1.0

**Comment by getActivity** [comment]
Demo有出现这个问题吗

**Comment by Redoteam** [comment]
6.0以下用的demo测试的
Toast结束程序会退出

**Comment by Redoteam** [comment]
上面图片贴的代码，是我这边处理的方式

**Comment by getActivity** [comment]
6.0以上要先处理悬浮窗权限：https://github.com/getActivity/XXPermissions

**Comment by getActivity** [comment]
用Demo测试 6.0以下用activity创建，Toast结束会导致退出程序

小伙子，我代码没写finishActivity啊，你这是不是崩溃还是其他什么的

**Comment by Redoteam** [comment]
好的，谢谢

**Comment by Redoteam** [comment]
我自己程序用的时候，4.4.4有崩溃Hardware acceleration can only be used with a single UI thread.具体的我等会看看能不能复现

**Comment by Redoteam** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/17085002/54105421-f3611400-440d-11e9-8d3a-632e9b998914.png">
这个是Android 4.4.4 用的activity创建的

**Comment by Redoteam** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/17085002/54105470-1be90e00-440e-11e9-8b10-a4e33e6c0ba6.png">
这个是用的Demo的

**Comment by getActivity** [comment]
换个其他4.4手机试试，说不定只是这个手机的Bug

**Comment by getActivity** [comment]
看看是不是这个问题：https://blog.csdn.net/u013424496/article/details/52995115

**Comment by Redoteam** [comment]
好的，谢谢，不过我也不清楚是不是
