### ISSUE TITLE
自定义布局

### ISSUE THREAD

**Issue by hudafei1225** [getActivity/XToast#20]
填充自定义布局，里面有个进度条pb，怎么动态去获取子view更新进度

**Comment by getActivity** [comment]
小伙子，XToast 里面有 findViewById 方法的，你可以用这个方法先获取到 View，然后再更新进度即可。

**Comment by getActivity** [comment]
小伙子，你看看你这边还有其他问题不？没有的话我就关闭 issue 了。

**Comment by hudafei1225** [comment]
> 小伙子，你看看你这边还有其他问题不？没有的话我就关闭 issue 了。

ok，谢谢
