### ISSUE TITLE
拖动事件与点击事件冲突

### ISSUE THREAD

**Issue by Felix1030** [getActivity/XToast#21]
三星s8  设置自定义View  点击事件框会抖动  不响应具体View的事件  DEMO必现

**Comment by Felix1030** [comment]
DEMO 点我消失 弹窗也是好久点不到

**Comment by getActivity** [comment]
小伙子，我使用小米 9 （Android 10），红米 K20 （Android 11），安卓官方模拟器（Android 10、Android 11）进行了测试，并没有发现你说的这个问题。

**Comment by Felix1030** [comment]
我这边用的是Piexl4 没问题，手头上只有三星s8曲面屏  现在点击事件要点N次才能响应

**Comment by Felix1030** [comment]
目前感觉是判定最小的滑动距离有些问题，我这边修改了一下根据系统的最小判定 目前可以实现需求  代码如下
`class CustomSpringDraggable : SpringDraggable() {

    private val mTouchSlop : Int = ViewConfiguration.get(getAppContext()).scaledTouchSlop

    override fun isTouchMove(downX: Float, upX: Float, downY: Float, upY: Float): Boolean {
        return abs(downX - upX) >= mTouchSlop || abs(downY - upY) >= mTouchSlop
    }
}`

**Comment by getActivity** [comment]
小伙子，麻烦你提供一下三星手机点击悬浮窗时的，down 和 up 触摸事件的 xy 坐标？你可以重写 Draggable 类中 onTouch 方法将坐标通过日志打印出来。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/133017301-2ccadc51-4b44-4325-9bed-c5d9f0b7dff3.png)

**Comment by Felix1030** [comment]
晚点我获取下，放出来

**Comment by getActivity** [comment]
好的，麻烦小伙子了

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/133017301-2ccadc51-4b44-4325-9bed-c5d9f0b7dff3.png)

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。

**Comment by Felix1030** [comment]
2021-09-20 12:13:55.987 27788-27788/com.voice.cn I/LogExt: SpringDraggable isTouchMove downX=119.41406 upX=119.7832 downY=117.01953 upY=117.77832
2021-09-20 12:13:56.005 27788-27788/com.voice.cn I/LogExt: SpringDraggable isTouchMove downX=119.41406 upX=120.48596 downY=117.01953 upY=119.98096
2021-09-20 12:13:56.021 27788-27788/com.voice.cn I/LogExt: SpringDraggable isTouchMove downX=119.41406 upX=120.82031 downY=117.01953 upY=121.38452
2021-09-20 12:13:56.040 27788-27788/com.voice.cn I/LogExt: SpringDraggable isTouchMove downX=119.41406 upX=119.00488 downY=117.01953 upY=118.848145

**Comment by Felix1030** [comment]
SpringDraggable isTouchMove downX=119.41406 upX=119.7832 downY=117.01953 upY=117.77832
SpringDraggable isTouchMove downX=119.41406 upX=120.48596 downY=117.01953 upY=119.98096
 SpringDraggable isTouchMove downX=119.41406 upX=120.82031 downY=117.01953 upY=121.38452
SpringDraggable isTouchMove downX=119.41406 upX=119.00488 downY=117.01953 upY=118.848145

**Comment by Felix1030** [comment]
以上是点击的时候的回调

**Comment by getActivity** [comment]
[XToast-8.3.aar.zip](https://github.com/getActivity/XToast/files/7195305/XToast-8.3.aar.zip)

**Comment by getActivity** [comment]
@Felix1030 小伙子，问题修复了，你用这个包再试试看

**Comment by Felix1030** [comment]
> @Felix1030 小伙子，问题修复了，你用这个包再试试看

好 我这边尝试下，然后回复

**Comment by Felix1030** [comment]
> > @Felix1030 小伙子，问题修复了，你用这个包再试试看
> 
> 好 我这边尝试下，然后回复

8.3版本 三星 s8 上面还是有一点问题  如果我拖动 然后停留不到边界  会自动触发点击事件

**Comment by getActivity** [comment]
@Felix1030 小伙子，我的手机测试是没有任何问题的，你可以加一下我的 QQ 880634 来联调这个问题。
