### ISSUE TITLE
设置全屏显示的悬浮窗

### ISSUE THREAD

**Issue by kokod21** [getActivity/XToast#22]
如题，想设置全屏显示的悬浮窗
布局中设置match_parent无效，
XToast.setHeight+XToast.setWidth，也无效
请问有啥方法可以设置悬浮窗全屏显示吗？

**Comment by getActivity** [comment]
[XToast-8.5.aar.zip](https://github.com/getActivity/XToast/files/7251004/XToast-8.5.aar.zip)

**Comment by getActivity** [comment]
@kokod21 小伙子，问题修复了，你用这个包再试试看。

**Comment by kokod21** [comment]
> [XToast-8.5.aar.zip](https://github.com/getActivity/XToast/files/7251004/XToast-8.5.aar.zip)

大佬这个包可以，能够全屏显示。
但是全屏效果没有延伸到状态栏，这个效果能够实现吗？

**Comment by getActivity** [comment]
* 小伙子，你用这两句代码试一下

```java
setWindowFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
setSystemUiVisibility(View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_FULLSCREEN)
```

**Comment by kokod21** [comment]
> * 小伙子，你用这两句代码试一下
> 
> ```java
> setWindowFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
> setSystemUiVisibility(View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_FULLSCREEN)
> ```

这样设置冒失不行，有2个问题（如下图）
1.悬浮窗没有衍生到状态栏
2.Activity倒是被迫衍生到状态栏去了

PS：我暂时不管这个效果了，今天要发版上线，谢谢大佬
![image](https://user-images.githubusercontent.com/5299774/135372877-8a8a3711-6361-42bd-8d35-5f8adea46780.png)

**Comment by zs1973** [comment]
后续这个问题解决了吗  貌似现在还是不能延伸到状态栏

**Comment by kokod21** [comment]
> 后续这个问题解决了吗 貌似现在还是不能延伸到状态栏

后续这个功能被砍了，我就没有关注这个了。。。

**Comment by actor20170211030627** [comment]
轮轮哥您适配一下啊, 我头都搞大了.
我这儿需求是<code>弹框半透明</code>, 加上你的那2句代码后, 就连带着<code>把Activity的状态栏都给隐藏了</code>, 但是Activity是要有状态栏的啊.

**Comment by getActivity** [comment]
@actor20170211030627 你把 `setWindowFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)` 代码去掉即可。

**Comment by getActivity** [comment]
![](https://github.com/user-attachments/assets/9e24fff6-8524-4cd8-bda8-5bc68d95612f)

**Comment by actor20170211030627** [comment]
> @actor20170211030627 你把 `setWindowFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)` 代码去掉即可。

轮轮哥, 我说的不是这个哦, 我这儿需求是
1.弹框全屏(包括覆盖状态栏, 导航栏)
2.弹框半透明, 能看见底部内容.
3.弹框显示之后, 底部的Activity状态栏不能被隐藏掉了.

不过我已经用另外的方法实现了这个需求, 心累.
还是感谢轮轮哥了💓💖

**Comment by getActivity** [comment]
@actor20170211030627 你把解决方案写到 issue 评论区，后续可以供其他人参考
