### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by buptstone** [getActivity/XToast#24]
xtoast用的2.6版，xtoast内部会持有activity造成内存泄露

**Comment by getActivity** [comment]
小伙子，最新版有这个问题吗？

**Comment by buptstone** [comment]
> 小伙子，最新版有这个问题吗？

没有用最新版

> 小伙子，最新版有这个问题吗？

没有用最新版，应该是注册了activity生命周期，没有反注册导致的，请问哪个版本修复了这个问题呢

**Comment by getActivity** [comment]
@buptstone 小伙子，我觉得你这个问题都压根都不需要问我，你直接试一下不就知道了？
