### ISSUE TITLE
设置了显示底部，输入法起来时，不能被顶起

### ISSUE THREAD

**Issue by wangsuicheng** [getActivity/XToast#25]
需要做什么样的配置才能被顶起来吗

**Comment by getActivity** [comment]
* 小伙子，你看到这个方法了没？

![](https://user-images.githubusercontent.com/28616817/143864088-e7f2797c-acd4-498c-857b-8e19caed458c.png)

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by wangsuicheng** [comment]
设置成SOFT_INPUT_ADJUST_RESIZE或者SOFT_INPUT_ADJUST_PAN没效，是不是activity也要设置？

**Comment by getActivity** [comment]
小伙子，你试试看 Activity 的软键盘能不能被顶上去？

**Comment by wangsuicheng** [comment]
> 小伙子，你试试看 Activity 的软键盘能不能被顶上去？

manifest 里设置了windowSoftInputMode 也没效果，也是一直在底部悬浮，挡住输入法

**Comment by getActivity** [comment]
小伙子，你试一下 Demo 有没有这个问题？我试过了是没有问题的。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
