### ISSUE TITLE
拖动手松开后，会自动触发点击事件的回调

### ISSUE THREAD

**Issue by hpdx** [getActivity/XToast#26]

**Comment by getActivity** [comment]
[XToast-8.5.aar.zip](https://github.com/getActivity/XToast/files/7648353/XToast-8.5.aar.zip)

**Comment by getActivity** [comment]
小伙子，你试试看这个包有没有问题。

**Comment by getActivity** [comment]
小伙子，结果咋样了？还有你如果长时间不回复的话，我会认为你的问题已经解决了，我就会主动关闭这个 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。

**Comment by hpdx** [comment]
> 超过三天没有响应，关闭此 issue。
之前赶项目进度，已放弃使用这个库，改用其他更适合的库了。谢谢
