### ISSUE TITLE
XToast 和 ToastUtils 该如何选择？

### ISSUE THREAD

**Issue by bingdu0** [getActivity/XToast#28]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
XToast和ToastUtils 这两个命名，ToastUtils 好理解 ，就是Toast专用的，但是XToast 他可以用于悬浮窗，也可以实现popwindow ,也可以实现Toast ，这不知道该如何选择。总感觉ToastUtils 是基于XToast 实现的。

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
我只是一个想法，可不可以将他两整合在一起呢？这样就不用再纠结，该使用哪个，不该使用哪个。既然XToast 都能实现了，之前引的ToastUtils,是不是有点多余呢？但是把ToastUtils 全部替换成XToast 还有点工作量。

**Comment by getActivity** [comment]
吐司的需求用 ToastUtils，悬浮窗的需求用 XToast

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
