### ISSUE TITLE
提 issue 需知

### ISSUE THREAD

**Issue by getActivity** [getActivity/XToast#3]
Github沟通效率实在是很低下，大家伙有问题或者Bug直接到Q群78797078私信给我反馈就OK，我会尽快答复你的问题

**Comment by o199666** [comment]
如何单独改变 XToast布局中的控件属性，比如我在别处调用 这个控件改变textview的值?

**Comment by getActivity** [comment]
@o199666 小伙子，你可以试着直接修改控件，看看会不会生效，如果没有生效请调用一下 XToast 对象的 update 方法试试。

**Comment by cjecky** [comment]
XToast的悬浮框，如何实现拖动位置之后再每个页面位置也生效

**Comment by getActivity** [comment]
@cjecky 小伙子，关于这个问题我已经在 QQ 上面回复你了，请勿在多个地方重复提问
