### ISSUE TITLE
做了个悬浮菜单栏

### ISSUE THREAD

**Issue by CPC-Coder** [getActivity/XToast#30]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
* 点击按钮 会展开菜单    但是目前想点击菜单外面 先收缩菜单  请问怎么实现

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by CPC-Coder** [comment]
无法监听  外面的 点击    ,普通dialog点击外面  可以取消  类似这种效果

**Comment by getActivity** [comment]
你可以定义一个全屏铺满的 View，然后监听它的点击事件，在事件回调中关闭 XToast。

**Comment by CPC-Coder** [comment]
谢谢轮子哥
