### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by Horicer** [getActivity/XToast#31]
在悬浮窗上面放输入框可以直接编辑文本吗

**Comment by getActivity** [comment]
你试一下不就知道了？

**Comment by Horicer** [comment]
试了不行

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/171180356-dac872d8-daa9-4c94-a137-904e029b6aea.png)

**Comment by Horicer** [comment]
如果是全局的悬浮窗，上面有输入框，然后外层的APP也有输入框，这两个输入框都能编辑吗

**Comment by getActivity** [comment]
小伙子，我试了一下，确实有这个问题，但是你这边有好的解决方案吗？

**Comment by getActivity** [comment]
@Horicer 这个你可以研究一下，我这边的话暂时没有好的方案，也许谷歌就是这么设计。
