### ISSUE TITLE
请教关于点击穿透

### ISSUE THREAD

**Issue by gaoyuoppa** [getActivity/XToast#32]
* issue 是否有人曾提过类似的问题？ 没有

* 你觉得框架有什么不足之处？ 没有

好哥哥,点击穿透悬浮窗,执行悬浮窗下面的按钮或者其他,
 能实现吗,可以帮帮我吗.

**Comment by getActivity** [comment]
这个没有什么办法可以实现，不过建议你通过 View 添加到 Activity 的形式来做，这种应该可以满足你的需求。

**Comment by Xiaoben336** [comment]
> 这个需求改下windowmanger layoutparams的flag就可以

改成哪个flag
