### ISSUE TITLE
能否支持view的部分边界移动到屏幕外

### ISSUE THREAD

**Issue by jin123d** [getActivity/XToast#34]
## 建议收集

* issue 是否有人曾提过类似的问题？
       无

* 你觉得框架有什么不足之处？
      能否支持view部分边界移动到屏幕外。

* 你觉得该怎么去完善会比较好？

支持`FLAG_LAYOUT_NO_LIMITS`flag，目前我是通过设置这个flag，再在onTouch中处理边界问题。
```
WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS
```

**Comment by getActivity** [comment]
小伙子，框架本身就是支持设置移动到屏幕外的，就如按照你说的要加一个 flag 和在 onTouch 处理，但是这种场景是比较少的，是否有必要加入到框架中？

**Comment by jin123d** [comment]
> 小伙子，框架本身就是支持设置移动到屏幕外的，就如按照你说的要加一个 flag 和在 onTouch 处理，但是这种场景是比较少的，是否有必要加入到框架中？

嗯嗯，框架开放了drag方法外部设置确实比较方便。
我翻了一下源码没看到怎么设置到屏幕外的。如果我看漏了请指教一下谢谢。

(因为我目前是设置flag并且自己写了一个drag继承你的BaseDrag实现的。但是因为无法获取rootView的right/left(始终为0)，所以目前只能靠设置x和y的偏移才能实现。)

使用场景的话可能确实比较少。此issue可以关闭。
