### ISSUE TITLE
竖屏切换至横屏之后悬浮窗位置显示异常

### ISSUE THREAD

**Issue by zs1973** [getActivity/XToast#35]
#### 问题描述

* 框架版本【必填】:v8.5

* 问题描述【必填】:悬浮窗在横屏状态下显示之后然后将屏幕切为横屏模式，悬浮窗位置显示异常。

* 复现步骤【必填】：竖屏状态下显示悬浮穿，然后将应用切换为横屏显示，悬浮窗位置发生变化。

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：所有机型

* 出现问题的安卓版本【必填】：所有版本

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是
* 
* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 WindowManager 是否也会出现该问题【非必答】：是

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

https://user-images.githubusercontent.com/8916333/193538213-dddcf2c8-6392-4441-a09f-1daad632c3cd.mp4

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
[XToast-8.6.aar.zip](https://github.com/getActivity/XToast/files/9702518/XToast-8.6.aar.zip)

**Comment by getActivity** [comment]
小伙子， 问题已经修正了，你可以下载上面的 aar 包测试一下。

**Comment by zs1973** [comment]
> 

嗯嗯 我测试一下 刚从家回到公司

**Comment by zs1973** [comment]
> 小伙子， 问题已经修正了，你可以下载上面的 aar 包测试一下。

可以直接发一下改动的代码吗 我是直接以引入源码的方式引用的这个lib

**Comment by zs1973** [comment]
> > 小伙子， 问题已经修正了，你可以下载上面的 aar 包测试一下。
> 
> 可以直接发一下改动的代码吗 我是直接以引入源码的方式引用的这个lib
我复制了新增的那个ScreenOrientationMonitor类和它的引用代码 运行之后貌似没有效果

**Comment by getActivity** [comment]
@zs1973 小伙子，不行哦，你只能用我发的 aar 做测试，主要原因有两个：

1.  aar 包中的代码是只读的，可以保证内容不被篡改
2. aar 包中的代码是测试的，还没有正式对外发布
3. 我不希望别人直接引用源码，如果有人那么做，后续如果有出现任何问题我这边一概不受理

**Comment by zs1973** [comment]
> @zs1973 小伙子，不行哦，你只能用我发的 aar 做测试，主要原因有几个：
> 
> 1. aar 包中的代码是只读的，可以保证内容不被篡改
> 2. aar 包中的代码是测试的，还没有正式对外发布
> 3. 我不希望别人直接引用源码，如果有人那么做，后续如果有出现任何问题只能靠你自己修复了，我不会基于你的代码进行单独维护

嗯嗯 我换回远程依赖  我先写完本期的需求再来测一下这个aar的

**Comment by zs1973** [comment]
> @zs1973 小伙子，不行哦，你只能用我发的 aar 做测试，主要原因有几个：
> 
> 1. aar 包中的代码是只读的，可以保证内容不被篡改
> 2. aar 包中的代码是测试的，还没有正式对外发布
> 3. 我不希望别人直接引用源码，如果有人那么做，后续如果有出现任何问题只能靠你自己修复了，我不会基于你的代码进行单独维护

可以了测过了 没问题  可以发新版本了。另外请教个问题哇，如果我想给悬浮窗的contentview 适配 layout-land 布局，我刚才试了一下，给新建一个横向的布局，在横竖屏切换时并不会自动启用横屏的布局呢

**Comment by getActivity** [comment]
@zs1973 小伙子，这个横屏切竖屏布局的实现，只能建议你通过代码自己实现了，因为 UI 变化了，View 对象就不是同一个对象了，所以我就算强制通过 ViewId 刷新了 View 布局，里面的状态和数据我都是没办法帮你迁移过来的。

**Comment by getActivity** [comment]
@zs1973 还有小伙子，你先用这个包，等过一段时间，我会更新远程依赖上去的。

**Comment by zs1973** [comment]
通过setcontentview设置布局id吗&nbsp; 然后再重新show?

**Comment by getActivity** [comment]
> 通过setcontentview设置布局id吗&nbsp; 然后再重新show?

@zs1973 是的，你可以这样做
