### ISSUE TITLE
全局模式悬浮窗的触摸式事件无法透传到桌面

### ISSUE THREAD

**Issue by pichsy** [getActivity/XToast#37]
全局模式悬浮窗的触摸式事件无法透传到桌面

* 框架版本【必填】：implementation 'com.github.getActivity:XToast:8.9'

* 问题描述【必填】：我要做一个护眼蒙层，全局的那种，使用时发现悬浮窗的触摸式事件无法透传到桌面

* 复现步骤【必填】：

* 是否必现【必填】：是，

* 出现问题的手机信息【必填】：华为荣耀30pro

* 出现问题的安卓版本【必填】：鸿蒙os 3.0 

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部，所有机型都不能透传事件

* 使用原生的 WindowManager 是否也会出现该问题【非必答】：鸿蒙2.0不会出现，鸿蒙3.0会，Android部分机型荣耀50系列会出现

 XToast<XToast<*>>(this.application).apply {
            val coverLayout = FrameLayout(this)
            contentView = coverLayout
            setWidth( XDisplayHelper.dp2px(applicationContext,180f))
            setHeight( XDisplayHelper.dp2px(applicationContext,180f))
            coverLayout.setBackgroundColor(Color.RED)
            setGravity(Gravity.TOP or Gravity.START)
            setOutsideTouchable(true)
            setDraggable(null)
            setOnTouchListener { toast, view, event ->
                false
            }
            show()
        }
        
使用方式如上，悬浮窗 内的触摸事件无法透传下去。
请大佬看看！

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
