### ISSUE TITLE
设置拖拽可以在开启后再关闭吗？

### ISSUE THREAD

**Issue by BZyanshui** [getActivity/XToast#38]
版本：框架版本【必填】：8.9

问题描述【必填】：设置拖拽可以在开启后再关闭吗？

复现步骤【必填】：无

是否必现【必填】：无

出现问题的手机信息【必填】：

出现问题的安卓版本【必填】：

问题信息的来源渠道【必填】：使用发现

请回答
是部分机型还是所有机型都会出现【必答】：全部

框架最新的版本是否存在这个问题【必答】：是

是否已经查阅框架文档还未能解决的【必答】：是

issue 是否有人曾提过类似的问题【必答】：否

是否可以通过 Demo 来复现该问题【必答】：是

使用原生的 WindowManager 是否也会出现该问题【非必答】：是/否（排查一下是不是框架的代码存在问题导致的）

**Comment by BZyanshui** [comment]
toast.setDraggable()   感觉这个方法传个true or false 来控制 拖拽是不是会更灵活一点

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于建议，不能提 bug issue 单，请提建议 issue 单

请重新提一个 issue 并纠正以上问题

**Comment by BZyanshui** [comment]
这个建议的issue在哪里有模板。我重新写一下

**Comment by getActivity** [comment]
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/28616817/236206841-6d73c03f-931e-4beb-b31f-21b310a52201.png">

**Comment by getActivity** [comment]
你 [new issue](https://github.com/getActivity/XToast/issues/new/choose) 的时候就能看到了
