### ISSUE TITLE
自定义动画问题

### ISSUE THREAD

**Issue by wp529** [getActivity/XToast#5]
前段时间接到个需求，需要自定义toast弹出动画。我们都知道原生的toast是不支持的，就算反射修改也不行，具体为什么我没找到源码，但我揣测只要type为toast的window，系统在加载动画时根本不管你设置的什么，只会取系统的动画。所以想到你这种用WindowManager来实现，但在已经弹出popup时再弹自定义的toast是会被popup遮挡的，尽管我设置的type比popup的大，也会被遮挡，使用你这个库也是一样的，大佬还有其他什么方法吗？

**Comment by getActivity** [comment]
我没有遇到过这类需求，还有XToast的功能我已经完全开放出来了，API 和 WindowManager 基本是一致的，你如果有这个需求，我建议你进一步了解 WindowManager
