### ISSUE TITLE
点击悬浮窗会跳动

### ISSUE THREAD

**Issue by 211885646** [getActivity/XToast#8]
实际使用过程中发现悬浮窗在屏幕左边贴边的时候点击会左右跳动一下,在右边就不会,demo中是一样的,并且demo中的全局悬浮窗点击跳转拨号相当难成功,应该是有事件冲突了

**Comment by getActivity** [comment]
我已经修复此问题，并在 QQ 中进行了答复。修复的问题将在下个版本发布。
